Repository Dylan-Gresham/BookTrack, pull requests merged in 2024-10, with the labels that each got.

#15 Update `BookType` to allow for lists (Task)
  src/app/lib/booklist.ts
Labels: frontend, ui, ux, ts

#16 Create `changeBookList` function (Task)
  src/app/lib/booklist.ts
Labels: frontend, ux, ts

#17 Add registeredBookListsAtom
  src/app/lib/atoms.ts
  src/app/library/page.tsx
Labels: enhancement, frontend, ts, needs review

#19 Add default book lists to default config
  src-tauri/src/config.rs
  src-tauri/src/main.rs
Labels: backend, rs, needs review

#27 Implement Book Component w/out Progress Bar [Task]
  next.config.js
  src/app/components/book.tsx
  src/app/edit-book/page.tsx
  src/app/library/page.tsx
  src/app/page.tsx
  src/app/styles/book.module.css
  src/app/styles/library.module.css
Labels: frontend, ui, ux, css, ts, db, priority-high, needs review

#28 Implemented Progress Bars [Task]
  package.json
  src-tauri/src/config.rs
  src-tauri/src/main.rs
  src/app/components/book.tsx
  src/app/create-account/page.tsx
  src/app/lib/booklist.ts
  src/app/library/page.tsx
  src/app/styles/book.module.css
  src/app/styles/library.module.css
  yarn.lock
Labels: frontend, ui, ux, css, ts, db, priority-low, needs review

#30 Fix Security Warnings from Dependabot [Task]
  next-env.d.ts
  package.json
  yarn.lock
Labels: frontend, priority-medium, needs review

#35 Support using dev database (Task)
  next-env.d.ts
  src-tauri/src/main.rs
Labels: frontend, backend, ts, rs, db, priority-medium, needs review
